package com.waectr.blog.dataobject;

import java.util.Date;

public class BlogDO {

    private Integer id;

    private String title;

    private String content;

    private String firstpicture;

    private String flag;

    private Integer views;

    private Integer appreciation;

    private Integer sharestatement;

    private Integer commentabled;


    private Integer published;

    private Integer recommend;

    private Date createTime;

    private Date updateTime;

    private Integer typeId;

    private Integer userId;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.title
     *
     * @return the value of t_blog.title
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.title
     *
     * @param title the value for t_blog.title
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.content
     *
     * @return the value of t_blog.content
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.content
     *
     * @param content the value for t_blog.content
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.firstPicture
     *
     * @return the value of t_blog.firstPicture
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public String getFirstpicture() {
        return firstpicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.firstPicture
     *
     * @param firstpicture the value for t_blog.firstPicture
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public void setFirstpicture(String firstpicture) {
        this.firstpicture = firstpicture == null ? null : firstpicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.flag
     *
     * @return the value of t_blog.flag
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.flag
     *
     * @param flag the value for t_blog.flag
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.views
     *
     * @return the value of t_blog.views
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public Integer getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.views
     *
     * @param views the value for t_blog.views
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public void setViews(Integer views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.appreciation
     *
     * @return the value of t_blog.appreciation
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public Integer getAppreciation() {
        return appreciation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.appreciation
     *
     * @param appreciation the value for t_blog.appreciation
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public void setAppreciation(Integer appreciation) {
        this.appreciation = appreciation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.shareStatement
     *
     * @return the value of t_blog.shareStatement
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public Integer getSharestatement() {
        return sharestatement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.shareStatement
     *
     * @param sharestatement the value for t_blog.shareStatement
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public void setSharestatement(Integer sharestatement) {
        this.sharestatement = sharestatement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.commentabled
     *
     * @return the value of t_blog.commentabled
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public Integer getCommentabled() {
        return commentabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.commentabled
     *
     * @param commentabled the value for t_blog.commentabled
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public void setCommentabled(Integer commentabled) {
        this.commentabled = commentabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.published
     *
     * @return the value of t_blog.published
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public Integer getPublished() {
        return published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.published
     *
     * @param published the value for t_blog.published
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public void setPublished(Integer published) {
        this.published = published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.recommend
     *
     * @return the value of t_blog.recommend
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.recommend
     *
     * @param recommend the value for t_blog.recommend
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.create_time
     *
     * @return the value of t_blog.create_time
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.create_time
     *
     * @param createTime the value for t_blog.create_time
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.update_time
     *
     * @return the value of t_blog.update_time
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.update_time
     *
     * @param updateTime the value for t_blog.update_time
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.type_id
     *
     * @return the value of t_blog.type_id
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.type_id
     *
     * @param typeId the value for t_blog.type_id
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.user_id
     *
     * @return the value of t_blog.user_id
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.user_id
     *
     * @param userId the value for t_blog.user_id
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}