package com.waectr.blog.dataobject;

public class BlogAndTagDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_tag.tag_id
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    private Integer tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_tag.blog_id
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    private Integer blogId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_tag.tag_id
     *
     * @return the value of t_blog_tag.tag_id
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_tag.tag_id
     *
     * @param tagId the value for t_blog_tag.tag_id
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_tag.blog_id
     *
     * @return the value of t_blog_tag.blog_id
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_tag.blog_id
     *
     * @param blogId the value for t_blog_tag.blog_id
     *
     * @mbg.generated Sun Dec 15 20:26:20 CST 2019
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }
}